### ISSUE TITLE
Buypass 2fa token?

### ISSUE THREAD

**Issue by vlori2k** [0xfff0800/snap0x#11]
Has anyone tested this, can this script be used to buypass the 2FA token?

**Comment by NotoriousG3** [comment]
> Has anyone tested this, can this script be used to buypass the 2FA token?

DId you find a way to bypass 2fa? there was a working one 2 days ago that just got patched, it involved browser, now it's gone , wondering if anybody had a working one to right now.

**Comment by 0xfff0800** [comment]
Soon I will do that stay tuned

**Comment by vlori2k** [comment]
Dont believe it until i see it

**Comment by Aliiiiiiiiii1** [comment]
key:3e97ccd60

**Comment by Aliiiiiiiiii1** [comment]
حولت ١٠٠ ريال ولا جاني الرابط ماتفعل شلون

**Comment by 0xfff0800** [comment]
التحميل من هنا :

https://github.com/0xfff0800/snap0x/releases/tag/1.0.9

**Comment by vlori2k** [comment]
Im still waiting for the opportunity to bruteforce  2FA on a snapchat user which i know the password on ?

**Comment by Aliiiiiiiiii1** [comment]
e0d2a73ac9b86481dbd234639085ef5d13095af3

**Comment by vlori2k** [comment]
English please ?

**Comment by 0xfff0800** [comment]
Added Buypass 2fa in Beta 2.0.3 

![B4DF6F7D-2341-4C4F-B8C6-79213FDC90D3](https://github.com/0xfff0800/snap0x/assets/55315423/04ae5349-702a-473a-81c3-0494a17ab8e9)

**Comment by 0xfff0800** [comment]
The topic will be closed after adding the required features in the current version 2.0.4, without any programming errors and functioning properly. Thank you all for your active participation
