### ISSUE TITLE
Snap0x Key

### ISSUE THREAD

**Issue by Antonio170423** [0xfff0800/snap0x#35]
I DOWNLOAD THE APP USING FLEKSTORE, I TRY LOGGING IN WITH MY ACCOUNT AND DID NOT WOR SO I CREATED AND ACCOUNT AND AFTER I CLICK SUBMIT, I NOTICED I TYPE THE WRONG EMAIL. NOW IS ASKING FOR A "KEY" WHICH I HAVE NOT RECEIVED BECAUSE I WROTE WRONG EMAIL, WHAT CAN I DO?

**Comment by Antonio170423** [comment]
JUST TO ADD THAT IF I DELETE THE snap0x app and install it again when i open the app it takes me to the same page of "Enter your Key".

**Comment by BAZ00KAB00MBAP** [comment]
Yes same issue with me, the "key" is no where on my receipt or invoice & I haven't been able to even login to the app & I've had it for 2 weeks, so half of the month is gone to absolutely nothing.

**Comment by 0xfff0800** [comment]
Can you contact us via email to help you ? 

 @BAZ00KAB00MBAP @Antonio170423 : 

- Email : flaaah777@gmail.com

**Comment by BAZ00KAB00MBAP** [comment]
Yes. I have.--Sent from Yandex Mail for mobile23.02.2024, 14:15, "0x" ***@***.***>:
Can you contact us via email to help you ?
@BAZ00KAB00MBAP @Antonio170423 :

Email : ***@***.***

**Comment by BAZ00KAB00MBAP** [comment]
Hello I still haven't received the help I need to login & behind using the app--Sent from Yandex Mail for mobile23.02.2024, 21:54, "Bazooka Joe" ***@***.***>:Yes. I have.--Sent from Yandex Mail for mobile23.02.2024, 14:15, "0x" ***@***.***>:
Can you contact us via email to help you ?
@BAZ00KAB00MBAP @Antonio170423 :

Email : ***@***.***

**Comment by 0xfff0800** [comment]
Please send us the order invoice number and we will review it with the team @BAZ00KAB00MBAP

**Comment by BAZ00KAB00MBAP** [comment]
> Please send us the order invoice number and we will review it with the team @BAZ00KAB00MBAP 

OK here is the invoice order number #57127667
& 2 fotos of the screen that I see after I plug in my key. 

1) it shows that it's loading...
2) screen shows the same thing as though I never tried to login after entering my key 

![image](https://github.com/0xfff0800/snap0x/assets/141020707/b91bc34a-0ac0-49e2-bc86-9b7bc2facb50)

![image](https://github.com/0xfff0800/snap0x/assets/141020707/23844f65-ddb3-47e7-a2c1-2100594fb340)
