### ISSUE TITLE
مش شغاله 

### ISSUE THREAD

**Issue by qq7qq** [0xfff0800/snap0x#5]
الاسكربت بتفضل شغاله علي فاضي مش فعاله

**Comment by 0xfff0800** [comment]
للاسف سناب شات تراقب الطلبات اذا لاحظت نشاط غريب يتم حظر الشبكه 
https://support.snapchat.com/ar-AA/a/blocked-network

لان المستخدمين عددهم كثير الي يستخدمون الاداة المجانيه 
عكس المدفوعه تكون نسخه لحالك بدون حظر
